language: java
sudo: true

install:
  - wget https://bintray.com/chrislusf/seaweedfs/download_file?file_path=go_0.70_amd64.deb -O weed.deb
  - sudo dpkg -i weed.deb
  - weed version
  - weed server -master.port=9333 -volume.port=9443 -volume.max=10 -master.volumeSizeLimitMB=30 &
  - weed server -master.port=9334 -volume.port=9444 -volume.max=10 -master.volumeSizeLimitMB=30 -master.peers=0.0.0.0:9333 &
  - weed server -master.port=9335 -volume.port=9445 -volume.max=10 -master.volumeSizeLimitMB=30 -master.peers=0.0.0.0:9334 &

script:
  - gradle test -i

after_success:
  - bash <(curl -s https://codecov.io/bash)